version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: pms
      MYSQL_PASSWORD: pms
      MYSQL_ROOT_PASSWORD: pms
      MYSQL_DATABASE: pms2DB
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db