version: '3'

services:

  mySQL:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: pms
      MYSQL_PASSWORD: pms
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pms2
    volumes:
      - ./sql_Scripts:/docker-entrypoint-initdb.d
#      - mydata:/home/mororo/Desktop/Docker-Persistence/PMS2
#volumes:
#  mydata:

#  adminer:
#    image: adminer
#    ports:
#      - "8083:8083"
#    depends_on:
#      - mySQL
#    links:
#      - mySQL

  redis:
    image: redis
#    command: redis-server --requirepass senha
    ports:
      - "6379:6379"